version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      # root credentials: root/your_root_password
      MYSQL_ROOT_PASSWORD: your_root_password
      # user credentials: your_database_user/your_database_password
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
      # database created on init container
      MYSQL_DATABASE: watch_shop
    ports:
      - 3306:3306
    volumes:
      - watch_shop:/var/lib/mysql
      - ./_db/watch_shop.sql:/docker-entrypoint-initdb.d/watch_shop.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: your_root_password
  # node:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: npm install && npm start
  #   depends_on:
  #     - db
volumes:
  watch_shop: